Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 4.2
  TargetRubyVersion: 2.3

Lint/RescueWithoutErrorClass:
  Exclude:
    - 'lib/traceable.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Max: 110 # Default: 80
  Exclude:
    - 'spec/**/*.rb'

Metrics/MethodLength:
  Max: 15

Rails/SkipsModelValidations:
  Exclude:
    - 'spec/**/*.rb'

Style/Documentation:
  # This cop checks for missing top-level documentation of classes and modules.
  # Classes with no body and namespace modules are exempt from the check.
  # Namespace modules are modules that have nothing in their bodies except
  # classes or other modules.
  Enabled: false

Style/FrozenStringLiteralComment:
  # `when_needed` will add the frozen string literal comment to files
  # only when the `TargetRubyVersion` is set to 2.3+.
  # `always` will always add the frozen string literal comment to a file
  # regardless of the Ruby version or if `freeze` or `<<` are called on a
  # string literal. If you run code against multiple versions of Ruby, it is
  # possible that this will create errors in Ruby 2.3.0+.
  #
  # See: https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3
  EnforcedStyle: when_needed
  Enabled: true
